# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cea6dae0d14a4c62d799dcf843dd2f91767f50b37b2e74dcd3a5f0cd7dfb33a862d5210774fb2fc3ed10a0ea99b51111459e346f47aa9416e861eb8dd13a4102

test:
  secret_key_base: 31a8aae7b490849f72e588c1453eeb5f758d7ce0663b5aaa297fe1975ea76f4cd688f3241f68c88d587473767125bde04fefd08b7fdd94f97c5af54578229476

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
